= Документация для разработчиков

Проект представляет собой обычное SpringBoot приложение, написанное на Java 15, с JPA в виде Hibernate.
Для доступа к данным используются репозитории Spring (см. `ru.sberbank.pprb.sbbol.draft.repository.DraftRepository`).

Приложение запускается локально на Postgres и обращается к БД напрямую.
Для трайба ДЦКБ команды могут создать БД в Postgress через [Jenkins job](https://sbt-jenkins.sigma.sbrf.ru/jenkinsint/job/DCB/job/service-jobs/job/create-postgres/)
Или использовать Docker для локальной работы - является предпочтительным вариантом.

Конфигурация StandIn находится в классе `ru.sberbank.pprb.sbbol.draft.config.AppJournalConfiguration`. Там объявлены
2 бина: плагин для настройки отправки векторов изменений в прикладной журнал и сервис, подписывающийся на сообщения
прикладного журнала и осуществляющий репликацию данных на другой контур.

Все параметры подключения к БД объявлены в конфигурации `ru.sberbank.pprb.sbbol.draft.config.DataSourceConfiguration`.
На уровне плагина реализуется подмена DataSource при переходе в SI и обратно в MAIN.

В тестах дополнительно подключена платформенная библиотека `sbp.integration.orm:orm-tests-common` для тестов
механизма репликации на заглушках. Благодаря конфигурации `ru.sberbank.pprb.sbbol.draft.TestReplicationConfiguration`
без отправки в Kafka реализуется вызов формирования вектора изменений и его применение на другой базе. Таким образом
тесты могут отловить ошибки конфигурации (например, объединение сущностей с разным ключом хэширования в одной
транзакции). Без заглушки приложение локально с флагом `standin.cloud.client.stub=true` работает без какой-либо
логики репликации.

Все контроллеры написаны самостоятельно. Клиент для тестов генерируется по схеме OpenApi (openapi/openapi.yml),
проверяя совместимость сервера с описанной спецификацией. Для подключения минимального количества дополнительных
зависимостей для задачи `openApiGenerate` выбрана библиотека генерации `native`.

Для создания докер-образа приложения в папке docker лежит `Dockerfile`.

== Установка сертификатов

Для сборки проекта необходимо установить корневой сертификат и сертификат удостоверяющего центра.
Скачать их можно по [ссылке](https://pking.sberbank.ru/)
Или получить с помощью команды:
```
openssl s_client -connect nexus-ci.delta.sbrf.ru:443 -showcerts
```

Для установки надо перейти в папку ~/.gradle (~ это домашняя директория) и выполнить команды

[source]
----
keytool -import -trustcacerts -alias SberCaExt -file путь_до/sberca-ext.pem -keystore cacerts -storepass changeit
keytool -import -trustcacerts -alias SberCaRootExt -file путь_до/sberca-root-ext.pem -keystore cacerts -storepass changeit
----

В файле `~/.gradle/gradle.properties` (если файла нет, необходимо его создать) добавить две строки, про путь и пароль к сертификатам.

[source]
----
systemProp.javax.net.ssl.trustStore=/Users/<ваш логин>/.gradle/cacerts
systemProp.javax.net.ssl.trustStorePassword=changeit
----

== Сборка проекта

Необходимо добавить креды для gradle.
Необходимо залогиниться в https://nexus-ci.sigma.sbrf.ru/ и в управлении аккаунтом (manage account) получить User Token
для своей учетной записи. После этого указать в ~/.gradle/gradle.properties:

[source]
----
systemProp.gradle.wrapperUser=<Your user token name code>
systemProp.gradle.wrapperPassword=<Your user token pass code>
tokenName=<Your user token name code>
tokenPassword=<Your user token pass code>
----

Проект собирается с помощью gradle командой

[source]
----
./gradlew build
----

== Запуск проекта

Проект запускается командой

[source]
----
./gradlew bootRun --args='--spring.profiles.active=dev'
----
Или через Idea с указанием профиля dev. Для запуска необходима БД Postgres (в докере или коммунальная).

== Запуск тестов

В тестах используется фреймворк testcontainers, который поднимает в Docker контейнеры с БД Postgres.

В случае использования удаленного Docker (на виртуалке из ДИ), необходимо в домашнюю директорию добавить файл
`.testcontainers.properties` (если файл уже есть, необходимо заменить) со следующим содержимым:

[source]
----
docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy
docker.tls.verify=1
# указать IP(XX.XX.XX.XX) виртуальной машины, полученной из ДИ
docker.host=tcp\://XX.XX.XX.XX\:2376
# указать полный путь к папке с сертификатами, полученными из ДИ
docker.cert.path=/Users/login/.docker/tls
----

== Создание файлов dependency-lock

Для создания dependency-lock файлов для gradle необходимо запустить таску

[source]
----
./gradlew resolveAndLockAll --write-locks
----

== Публикация API в META

Публикация вызывается командой

[source]
----
./gradlew clean build reverseAndPublish -x test
----

== Генерация sql патча

Генерация вызывается командой

[source]
----
./gradlew newpatch -Ppatchname=newpatch
----

Для изменения директории создания патча использовать с флагом

[source]
----
./gradlew newpatch -Ppatchname=newpatch -Preleaseversion='01.000.00'
----
или изменить версию в gradle.properties
