#Остается неизменной и не влияет на версию проекта при сборке на jenkins
#Влияет на директорию создания sql патча
version=01.002.00

standinPluginVersion=5.7.0

# увеличение metaspace для Sonar
org.gradle.jvmargs=-XX:MaxMetaspaceSize=512m

#TODO replace with component id from META
metamodel.componentCode=sber-business-api-sdk
metamodel.modelName=sber-business-api-sdk
metamodel.modelVersion=1.0.0
