---
systemIntegrationEntries:
  - Values.int.pprb.CI03132806_appjournal.v1_0
  - Values.int.pprb.dbMain.v1_0
  - Values.int.pprb.dbSi.v1_0
  - Values.int.pprb.CI03132782_audit.v1_0
  - Values.int.pprb.CI03132806_fluentbit.v1_0
  - Values.int.pprb.CI03132792_tsaKafka.v1_0
  - Values.int.sbbol.CI04302106_restIn.latest
  - Values.int.pprb.CI02745214_digitalapi.v1_0

intEntry:
  pprb:
    dbMain: Values.int.pprb.dbMain.v1_0
    dbSi: Values.int.pprb.dbSi.v1_0
    audit: Values.int.pprb.CI03132782_audit.v1_0
    digitalapi: Values.int.pprb.CI02745214_digitalapi.v1_0
    tsaKafka: Values.int.pprb.CI03132792_tsaKafka.v1_0
    appjournal: Values.int.pprb.CI03132806_appjournal.v1_0
    fluentbit: Values.int.pprb.CI03132806_fluentbit.v1_0
  sbbol:
    restIn: Values.int.sbbol.CI04302106_restIn.latest
  ott: Values.int.CI03132766_ott.v4g


