# В данный файл можно и нужно добавлять стендонезависимые параметры
# Нужно проставить свои актуальные значения, что бы на стендах их не переопределять каждый раз
app:
  application:
    name: sber-business-api-sdk  # нужно проставить актуальное значение
    contextRoot: /ic/ufs/sber-business-api-sdk  # нужно проставить актуальное значение
    appjournal:
      enabled: true

  fluentbit:
    moduleID: sber-business-api-sdk # спросить у сопровождения и поставить нужное значение
